@extends('admin.layouts.app')

@section('breadcrumb')
	<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
		<h4 class="page-title">Billing Section</h4>
	</div>
	<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-home"></i></a></li>
			<li>Transaction</li>
			<li>
				<a class="active" href="#">Billing</a>
			</li>
		</ol>
	</div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <div align="right">
                <label class="col-md-12">September 25, 2018 <!-- Autogenerated Date --></label>
            </div>
            <h3><b class="text-danger">Edward D. Cullen</b></h3> <!-- Autogenerated Name -->
            <p>Patients Name</p>
            <div class="row">
                <div class="col-md-6">
                    <div class="table-responsive m-t-40">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Service Name</th>
                                    <th class="text-right">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-center">1</td>
                                    <td>Medicines</td>
                                    <td class="text-right">1000 PHP</td>
                                </tr>
                                <tr>
                                    <td class="text-center">2</td>
                                    <td>X-ray Reports</td>
                                    <td class="text-right">1200 PHP</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                        </div>
                        <div class="col-md-6 text-right">
                        <label class="col-md-12">2200 PHP</label>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <form class="form-material">
                        <div class="row">
                            <div class="col-md-5">
                                <label class="col-md-12">Discount</label>
                            </div>
                            <div class="col-md-1">
                                <label class="col-md-12">:</label>
                            </div>
                            <div class="col-md-3">
                                <input type="radio" name="discount" value="percentage">Percentage<br>
                            </div>
                            <div class="col-md-3">
                                <input type="radio" name="discount" value="amount">Amount<br>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Enter here">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <label class="col-md-6">Discounted Price</label>
                            </div>
                            <div class="col-md-1">
                                <label class="col-md-6">:</label>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <p>900 PHP</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6">
                                <label class="col-md-12">Mode of Payment</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6">
                                <select class="form-control">
                                    <option> ... </option>
                                    <option> Half Payment </option>
                                    <option> Full Payment </option>
                                </select>
                            </div>
                        </div><br>
                        <div class="row">
                            <div class="col-md-6"><br>
                                <label class="col-md-12">Total Amount</label>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <h3 class="text-danger"><b> 900 PHP</b></h3>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div align="right">
                <a href="{{ route('transaction.receipt') }}" role="button" class="btn btn-info waves-effect waves-light m-r-10"><i class="fa fa-fw fa-lg fa-check-circle"></i>Proceed to Payment</a>
            </div>
        </div>
    </div>
</div>
@endsection
